[package]
name = "plotters"
version = "0.3.0-pre"
authors = ["Hao Hou <haohou302@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A Rust drawing library focus on data plotting for both WASM and native applications"
repository = "https://github.com/38/plotters"
homepage = "https://plotters-rs.github.io/"
keywords = ["WebAssembly", "Visualization", "Plotting", "Drawing"]
categories = ["visualization", "wasm"]
readme = "README.md"
exclude = ["doc-template/*"]

[dependencies]
num-traits = "0.2.11"
chrono = { version = "0.4.10", optional = true }
# Plotters backend deps
# TODO: Update the version when publish
plotters-backend = "0.0.*"
plotters-svg = {version = "0.1.*", optional = true}

[dependencies.plotters-bitmap]
version = "0.1.*"
optional = true
default_features = false

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rusttype = { version = "0.8.2", optional = true }
lazy_static = { version = "1.4.0", optional = true }
font-kit = { version = "0.5.0", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.image]
version = "0.22.4"
optional = true
default-features = false
features = ["jpeg", "png_codec", "bmp"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.58"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.35"
features = [
         "Document",
         "DomRect",
         "Element",
         "HtmlElement",
         "Node",
         "Window",
         "HtmlCanvasElement",
         "CanvasRenderingContext2d",
]

[features]
default = [
        "bitmap_backend", "bitmap_encoder", "bitmap_gif",
        "svg_backend",
        "chrono",
        "ttf",
        "image",
        "deprecated_items",  "all_series", "all_elements"
]
all_series = ["area_series", "line_series", "point_series"]
all_elements = ["errorbar", "candlestick", "boxplot", "histogram"]

# Tier 1 Backends
bitmap_backend = ["plotters-bitmap", "ttf"]
bitmap_encoder = ["plotters-bitmap/image_encoder"]
bitmap_gif = ["plotters-bitmap/gif_backend"]
svg_backend = ["plotters-svg"]

# Elements
errorbar = []
candlestick = []
boxplot = []

# Series
histogram = []
area_series = []
line_series = []
point_series = []

# Font implemnetation
ttf = ["font-kit", "rusttype", "lazy_static"]

# Misc
datetime = ["chrono"]
evcxr = ["svg_backend"]
deprecated_items = [] # Keep some of the deprecated items for backward compatibility

[dev-dependencies]
rand = "0.7.3"
itertools = "0.8.2"
rand_distr = "0.2.2"
criterion = "0.3.1"
rayon = "1.3.0"
rand_xorshift = "0.2.0"
plotters-bitmap = "0.1.*"

[[bench]]
name = "benchmark"
harness = false
path = "benches/main.rs"
